version: "3.8"

networks:
  app-network:
    name: app-network
    driver: bridge

services:

  mysql:
    container_name: mysql
    image: mysql
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./mysql-data
        target: /var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: webjox-personal-blog
      MYSQL_USER: webjox-personal-blog
      MYSQL_PASSWORD: webjox-personal-blog
    networks:
      - app-network

  php:
    container_name: php
    build: ./www
    volumes:
      - type: bind
        source: ./www
        target: /var/www
    networks:
      - app-network
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./docker/nginx/default.nginx
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./www
        target: /var/www
    networks:
      - app-network
    depends_on:
      - php
      - mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - target: 80
        published: 1500
        protocol: tcp
        mode: host
    environment:
      PMA_HOST: mysql
      PMA_USER: webjox-personal-blog
      PMA_PASSWORD: webjox-personal-blog
    networks:
      - app-network
    depends_on:
      - mysql
