<?php
/**
 * @var PhpRenderer|HelperTrait $this
 * @var Post[]                  $posts
 */

use Application\Model\Entity\Post;
use Laminas\Form\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

?>
<div class="row g-3">
    <div class="col-12">
        <div class="row g-3" id="post-list">
            <?php foreach ($posts as $post): ?>
                <div class="col-12">
                    <div class="card p-3">
                        <div class="row g-3">
                            <div class="col-12">
                                <p class="h4"><a href="<?= $this->url('post/edit',
                                        ['id' => $post->getId()]); ?>">Post #<?= $post->getId(); ?></a></p>
                            </div>
                            <div class="col-12">
                                <p class="mb-0"><?= $post->getContent(); ?></p>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
