<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer|Laminas\Form\View\HelperTrait $this
 * @var Laminas\Form\ElementInterface                                   $element
 * @var string|null                                                     $label
 * @var array|null                                                      $labelAttributes
 * @var string|null                                                     $labelPosition
 * @var bool                                                            $renderErrors
 */
?>
