<?php

declare(strict_types=1);

namespace Application\View\Helper;

use Laminas\Form\Element\MultiCheckbox as MultiCheckboxElement;
use Laminas\Form\ElementInterface;

class FormMultiCheckbox extends \Laminas\Form\View\Helper\FormMultiCheckbox
{
    /**
     * @inheritDoc
     */
    public function render(ElementInterface $element): string
    {
        return parent::render($element); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function renderOptions(
        MultiCheckboxElement $element,
        array $options,
        array $selectedOptions,
        array $attributes,
    ): string {
        return parent::renderOptions($element, $options, $selectedOptions, $attributes); // TODO: Change the autogenerated stub
    }
}
