<?php
/**
 * @var PhpRenderer|HelperTrait $this
 * @var CategoryForm            $categoryForm
 */

use Application\Form\Category\CategoryForm;
use Laminas\Form\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

$this->inlineScript()
    ->appendFile($this->basePath('js/jquery-3.7.1.min.js'))
    ->appendFile($this->basePath('js/collection-manipulation.js'));
?>
<?= $this->form()->render($categoryForm); ?>
