<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer|Laminas\Form\View\HelperTrait $this
 * @var Application\Form\Index\SignInForm                               $signInForm
 * @var Application\Form\Index\SignUpForm                               $signUpForm
 */
?>
<div class="row g-3">
    <div class="col-12">
        <div class="card p-4 sign-in-card">
            <h1 class="mb-3">Sign in</h1>
            <?= $this->form()->render($signInForm); ?>
        </div>
    </div>
    <div class="col-12">
        <div class="card p-4 sign-up-card">
            <h1 class="mb-3">Sign up</h1>
            <?= $this->form()->render($signUpForm); ?>
        </div>
    </div>
</div>
